FROM php:7.2-apache 

RUN cd /etc/apache2/mods-enabled && \
    ln -s ../mods-available/rewrite.load

RUN docker-php-ext-install mysqli
RUN docker-php-ext-install -j$(nproc) mysqli pdo_mysql
COPY ./000-default.conf /etc/apache2/sites-available/